/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.dwarfmod.dwarffortressmodmaker.gui;

import br.com.dwarfmod.dwarffortressmodmaker.core.ModManager;
import br.com.dwarfmod.dwarffortressmodmaker.data.Mod;
import br.com.dwarfmod.dwarffortressmodmaker.data.ModType;
import br.com.dwarfmod.dwarffortressmodmaker.utils.Constants;
import java.awt.Image;
import java.io.File;
import java.util.Arrays;
import java.util.TreeSet;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Ander
 */
public class ModInfoEditDialog extends javax.swing.JDialog {

    private final Mod selectedMod;
    private final ModManager manager;

    /**
     * Creates new form ModEditDialog
     */
    public ModInfoEditDialog(final java.awt.Frame parent, final boolean modal, final Mod selectedMod, final ModManager manager) {
        super(parent, modal);
        this.selectedMod = selectedMod;
        this.manager = manager;
        
        this.initComponents();
        this.fillImagePane();
        this.pack();
        
        
        this.okButton.setEnabled(selectedMod.getType() == ModType.MODMAKER);
        this.requiredIdsButton.setEnabled(selectedMod.getType() == ModType.MODMAKER);
        this.steamTagsButton.setEnabled(selectedMod.getType() == ModType.MODMAKER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        numericVersionField = new javax.swing.JTextField();
        displayedVersionField = new javax.swing.JTextField();
        earliestCompatibleNumericVersionField = new javax.swing.JTextField();
        earliestCompatibleDisplayedVersionField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        descriptionField = new javax.swing.JTextField();
        requiresIdBeforeMeField = new javax.swing.JTextField();
        requiredIdsButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        steamTitleField = new javax.swing.JTextField();
        steamTagField = new javax.swing.JTextField();
        steamChangelogField = new javax.swing.JTextField();
        steamFileIdField = new javax.swing.JTextField();
        steamTagsButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        imageScrollPane = new javax.swing.JScrollPane();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ModInfo Editor");
        setModal(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General Information"));

        jLabel1.setText("ID:");

        jLabel2.setText("Numeric Version:");

        jLabel3.setText("Displayed Version:");

        jLabel4.setText("Earliest Compatible Numeric Version:");

        jLabel5.setText("Earliest Compatible Displayed Version:");

        jLabel6.setText("Author:");

        jLabel7.setText("Description:");

        jLabel8.setText("Requires ID Before Me:");

        idField.setText(this.selectedMod.getId());

        numericVersionField.setText(this.selectedMod.getNumericVersion());

        displayedVersionField.setText(this.selectedMod.getEarliestCompatibleNumericVersion());

        earliestCompatibleNumericVersionField.setText(this.selectedMod.getEarliestCompatibleNumericVersion());

        earliestCompatibleDisplayedVersionField.setText(this.selectedMod.getEarliestCompatibleDisplayedVersion());

        authorField.setText(this.selectedMod.getAuthor());

        descriptionField.setText(this.selectedMod.getDescription());

        requiresIdBeforeMeField.setText(this.selectedMod.getRequiresIdBeforeMe().isEmpty() ? "" : String.join(", ", this.selectedMod.getRequiresIdBeforeMe()));

        requiredIdsButton.setText("...");
        requiredIdsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requiredIdsButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Name:");

        nameField.setText(this.selectedMod.getName());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorField)
                    .addComponent(idField)
                    .addComponent(numericVersionField)
                    .addComponent(displayedVersionField)
                    .addComponent(earliestCompatibleNumericVersionField)
                    .addComponent(earliestCompatibleDisplayedVersionField)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(requiresIdBeforeMeField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requiredIdsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numericVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(displayedVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(earliestCompatibleNumericVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(earliestCompatibleDisplayedVersionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(requiresIdBeforeMeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requiredIdsButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Steam Data"));

        jLabel9.setText("Steam Title:");

        jLabel10.setText("Steam Tags:");

        jLabel11.setText("Steam Changelog:");

        jLabel12.setText("Steam File ID:");

        steamTitleField.setText(this.selectedMod.getSteamTitle());

        steamTagField.setText(this.selectedMod.getSteamTags().isEmpty() ? "" : String.join(", ", this.selectedMod.getSteamTags()));
        steamTagField.setToolTipText("total conversion, balance, difficulty, qol, graphics, fix, cheat, tweak, ui, megabeast, entity, creature, material, inorganic, item , descriptor, building");

        steamChangelogField.setText(this.selectedMod.getSteamChangelog());

        steamFileIdField.setText(this.selectedMod.getSteamFileId());

        steamTagsButton.setText("...");
        steamTagsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steamTagsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(steamTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(steamTagField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(steamTagsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(steamFileIdField)
                            .addComponent(steamChangelogField))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(steamTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(steamTagField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(steamTagsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(steamChangelogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(steamFileIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Steam Mod Title Image"));

        imageLabel.setToolTipText("The preview.png at the root folder of the mod.");
        imageScrollPane.setViewportView(imageLabel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void steamTagsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steamTagsButtonActionPerformed
        String optionsString = steamTagField.getText();
        OptionsDialog optionsDialog = new OptionsDialog(null, "Options", optionsString, null);
        optionsString = optionsDialog.getResult();
        if (optionsString != null) {
            steamTagField.setText(optionsString);
        }
    }//GEN-LAST:event_steamTagsButtonActionPerformed

    private void requiredIdsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requiredIdsButtonActionPerformed
        String optionsString = requiresIdBeforeMeField.getText();
        OptionsDialog optionsDialog = new OptionsDialog(null, "Options", optionsString, this.buildModList());
        optionsString = optionsDialog.getResult();
        if (optionsString != null) {
            requiresIdBeforeMeField.setText(optionsString);
        }
    }//GEN-LAST:event_requiredIdsButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.selectedMod.setId(idField.getText().isEmpty() ? "" : idField.getText());
        this.selectedMod.setNumericVersion(numericVersionField.getText().isEmpty() ? "" : numericVersionField.getText());
        this.selectedMod.setDisplayedVersion(displayedVersionField.getText().isEmpty() ? "" : displayedVersionField.getText());
        this.selectedMod.setEarliestCompatibleNumericVersion(earliestCompatibleNumericVersionField.getText().isEmpty() ? "" : earliestCompatibleNumericVersionField.getText());
        this.selectedMod.setEarliestCompatibleDisplayedVersion(earliestCompatibleDisplayedVersionField.getText().isEmpty() ? "" : earliestCompatibleDisplayedVersionField.getText());
        this.selectedMod.setAuthor(authorField.getText().isEmpty() ? "" : authorField.getText());
        this.selectedMod.setName(nameField.getText().isEmpty() ? "" : nameField.getText());
        this.selectedMod.setDescription(descriptionField.getText().isEmpty() ? "" : descriptionField.getText());
        this.selectedMod.setSteamTitle(steamTitleField.getText().isEmpty() ? "" : steamTitleField.getText());
        this.selectedMod.setSteamChangelog(steamChangelogField.getText().isEmpty() ? "" : steamChangelogField.getText());
        this.selectedMod.setSteamFileId(steamFileIdField.getText().isEmpty() ? "" : steamFileIdField.getText());

        String requiresIdBeforeMeText = requiresIdBeforeMeField.getText().isEmpty() ? "" : requiresIdBeforeMeField.getText();
        this.selectedMod.setRequiresIdBeforeMe(new TreeSet<>());
        if (requiresIdBeforeMeText != null) {
            this.selectedMod.getRequiresIdBeforeMe().addAll(Arrays.asList(requiresIdBeforeMeText.split(",")));
        }

        String steamTagsText = steamTagField.getText().isEmpty() ? null : steamTagField.getText();
        this.selectedMod.setSteamTags(new TreeSet<>());
        if (steamTagsText != null) {
            this.selectedMod.getSteamTags().addAll(Arrays.asList(steamTagsText.split(",")));
        }
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorField;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JTextField displayedVersionField;
    private javax.swing.JTextField earliestCompatibleDisplayedVersionField;
    private javax.swing.JTextField earliestCompatibleNumericVersionField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane imageScrollPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField numericVersionField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton requiredIdsButton;
    private javax.swing.JTextField requiresIdBeforeMeField;
    private javax.swing.JTextField steamChangelogField;
    private javax.swing.JTextField steamFileIdField;
    private javax.swing.JTextField steamTagField;
    private javax.swing.JButton steamTagsButton;
    private javax.swing.JTextField steamTitleField;
    // End of variables declaration//GEN-END:variables

    private String[] buildModList() {
        return this.manager.getModList().stream().filter(x -> !x.getId().equals(this.selectedMod.getId())).map(Mod::getId).collect(Collectors.toList()).toArray(String[]::new);
    }

    private void fillImagePane() {
        try {
            final File file = new File(this.selectedMod.getModPath() + "\\" + Constants.STEAM_PREVIEW_IMAGE);
            if (!file.exists()) {
                this.imageLabel.setIcon(null);
                return;
            }

            Image image = ImageIO.read(file);

            this.imageLabel.setIcon(new ImageIcon(image));
        } catch (Exception e) {
            this.imageLabel.setIcon(null);
        }
    }
}
